### ISSUE TITLE
Too low indicator values for Sulpher

### ISSUE THREAD

**Issue by yuki-nmi** [AgroCares/Open-Bodem-Index-Calculator#74]
Most grassland parcels score very low for I_C_S (majority is I_C_S < 0.5), whereas all mais parcels scores 1. See figures below (of all dutch parcels). This is strange, as grassland and maisland have a similar range of A_S_TOT. Also in the field, it is observed that many mais parcels are associated with low classes of SLV (ref: den Boer et al. 2007 NMI rapport 1252.N.07). 

![image](https://user-images.githubusercontent.com/54851556/94578978-9b506380-0278-11eb-9078-f387ff5d333a.png)

After discussing with Wim Bussink, I made several adjustment for functions of D_SLV and I_C_S. See pull request #73.
These adjustments improve the evaluation of maisland to some extent. See figure below.

![image](https://user-images.githubusercontent.com/54851556/94579357-0437db80-0279-11eb-8e58-36d158d3ec57.png)

It is still questionable if the calculated D_SLV in OBIC is correct. Is it realistic that we have so many grassland parcels with low I_C_S?? We also need to check if our calculation of D_SLV for arable land is same as that of Eurofins. See the code of Arjan Reijneveld (Eurofins) here:
[Formule SLV.txt](https://github.com/AgroCares/Open-Bodem-Index-Calculator/files/5300267/Formule.SLV.txt)

**Comment by gerardhros** [comment]
The calculation of SLV originate from the current fertilizer recommenation manual (www.bemestingsadvies.nl).
So, there is no indication that there an error has occured. Looking to the original soil data for the Achterhoek, the total S content is on average 390 mg/kg for sandy soils (with a standard deviation of 530). On average, this means that half of the fields are in the class "low" with a SLV below 11 kg S / ha. So that suggests the national fertilizer manual need to be updated or accept the fact that soil quality needs some improvement here.

![image](https://user-images.githubusercontent.com/40168511/96098152-15682580-0ed2-11eb-9124-a7f21f80733d.png)

**Comment by wimlelystad** [comment]
Grassland checked on march 17. It is correct.
Maizeland:
Eurofins has changed the SLV calculation between 2013 and 2018. Or the calculation for arable land is different from

**Comment by gerardhros** [comment]
this has been solved in branch fy_sulpher_modify and has been merged into release/v1.0.0
